sudo: false
language: node_js
node_js:
  - "0.10"
before_install:
  - export TZ=Europe/London
  - "npm install -g bower"
  - "bower install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
